// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: task/conf/conf.proto

package conf

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App *App `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_conf_conf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_task_conf_conf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_task_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

type App struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BackupDbACron string `protobuf:"bytes,1,opt,name=backup_db_a_cron,json=backupDbACron,proto3" json:"backup_db_a_cron,omitempty"`
	BackupDbBCron string `protobuf:"bytes,2,opt,name=backup_db_b_cron,json=backupDbBCron,proto3" json:"backup_db_b_cron,omitempty"`
}

func (x *App) Reset() {
	*x = App{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_conf_conf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_task_conf_conf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_task_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *App) GetBackupDbACron() string {
	if x != nil {
		return x.BackupDbACron
	}
	return ""
}

func (x *App) GetBackupDbBCron() string {
	if x != nil {
		return x.BackupDbBCron
	}
	return ""
}

var File_task_conf_conf_proto protoreflect.FileDescriptor

var file_task_conf_conf_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x61, 0x73, 0x6b, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x2f, 0x63, 0x6f, 0x6e, 0x66,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x74, 0x61, 0x73,
	0x6b, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x3c, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x12, 0x2f, 0x0a, 0x03,
	0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x72, 0x6f, 0x6e,
	0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x41, 0x70, 0x70, 0x42, 0x08,
	0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x03, 0x61, 0x70, 0x70, 0x22, 0x69, 0x0a,
	0x03, 0x41, 0x70, 0x70, 0x12, 0x30, 0x0a, 0x10, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x64,
	0x62, 0x5f, 0x61, 0x5f, 0x63, 0x72, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x0d, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x44,
	0x62, 0x41, 0x43, 0x72, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x10, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x5f, 0x64, 0x62, 0x5f, 0x62, 0x5f, 0x63, 0x72, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x0d, 0x62, 0x61, 0x63, 0x6b, 0x75,
	0x70, 0x44, 0x62, 0x42, 0x43, 0x72, 0x6f, 0x6e, 0x42, 0x4c, 0x5a, 0x4a, 0x67, 0x69, 0x74, 0x63,
	0x64, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x73, 0x6b, 0x79, 0x67, 0x75, 0x61, 0x72, 0x64, 0x6d, 0x69,
	0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x67, 0x64, 0x74, 0x2f, 0x75, 0x72, 0x6c, 0x63,
	0x61, 0x74, 0x2d, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x3b, 0x63, 0x6f, 0x6e, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_task_conf_conf_proto_rawDescOnce sync.Once
	file_task_conf_conf_proto_rawDescData = file_task_conf_conf_proto_rawDesc
)

func file_task_conf_conf_proto_rawDescGZIP() []byte {
	file_task_conf_conf_proto_rawDescOnce.Do(func() {
		file_task_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(file_task_conf_conf_proto_rawDescData)
	})
	return file_task_conf_conf_proto_rawDescData
}

var file_task_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_task_conf_conf_proto_goTypes = []interface{}{
	(*Bootstrap)(nil), // 0: cron.task.conf.Bootstrap
	(*App)(nil),       // 1: cron.task.conf.App
}
var file_task_conf_conf_proto_depIdxs = []int32{
	1, // 0: cron.task.conf.Bootstrap.app:type_name -> cron.task.conf.App
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_task_conf_conf_proto_init() }
func file_task_conf_conf_proto_init() {
	if File_task_conf_conf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_task_conf_conf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bootstrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_conf_conf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_task_conf_conf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_conf_conf_proto_goTypes,
		DependencyIndexes: file_task_conf_conf_proto_depIdxs,
		MessageInfos:      file_task_conf_conf_proto_msgTypes,
	}.Build()
	File_task_conf_conf_proto = out.File
	file_task_conf_conf_proto_rawDesc = nil
	file_task_conf_conf_proto_goTypes = nil
	file_task_conf_conf_proto_depIdxs = nil
}
