// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.2
// - protoc             v4.25.1
// source: api/user-manage/v1/livez.proto

package adminv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationLivezServiceLivez = "/usermanage.admin.v1.LivezService/Livez"

type LivezServiceHTTPServer interface {
	Livez(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
}

func RegisterLivezServiceHTTPServer(s *http.Server, srv LivezServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/livez", _LivezService_Livez0_HTTP_Handler(srv))
}

func _LivezService_Livez0_HTTP_Handler(srv LivezServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLivezServiceLivez)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Livez(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type LivezServiceHTTPClient interface {
	Livez(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type LivezServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewLivezServiceHTTPClient(client *http.Client) LivezServiceHTTPClient {
	return &LivezServiceHTTPClientImpl{client}
}

func (c *LivezServiceHTTPClientImpl) Livez(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/livez"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLivezServiceLivez))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
