// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/EchoGroot/kratos-examples/backup-db/internal/task/biz"
	"github.com/EchoGroot/kratos-examples/backup-db/internal/task/conf"
	"github.com/EchoGroot/kratos-examples/backup-db/internal/task/server"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	backupDbUsecase := biz.NewBackupDbUsecase()
	backupDbServer := server.NewBackupDbServer(bootstrap, backupDbUsecase)
	app := newApp(backupDbServer)
	return app, func() {
	}, nil
}
